### ISSUE TITLE
run on Google Colab

### ISSUE THREAD

**Issue by kiashann** [benjamin-awd/monopoly#108]
Hi, thanks for your work.
How can I run these two instructions on Google Colab and install monopoly?

brew install make
make setup

**Comment by benjamin-awd** [comment]
Hey @kiashann, unfortunately it won't be possible to run this on Colab, since `monopoly` operates on Python 3.11, but it looks like Colab operates on 3.10.

https://colab.research.google.com/drive/18PwY9eAYxAyG8swpxbeX2DIYaoXzUWXI?usp=sharing

**Comment by benjamin-awd** [comment]
I've added support for 3.10, so this should now be possible
